### ISSUE TITLE
On page load

### ISSUE THREAD

**Issue by XsidX** [amejid/todo-list#2]
Impressed with the organization of your project, here are a few suggestions to improve on:
-it would be better to add the functionality displaying the list from the array in a function and call it when the page loads. You can check this [link](https://www.w3schools.com/jsref/event_onload.asp)

**Comment by amejid** [comment]
Thanks for the feedback,
The issue was addressed [here](https://github.com/amejid/todo-list/pull/3/commits/d5a8bab7c1dd51c91bed2eeeb1ea735f1d7fb25e#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R9-R11)
